<a href="https://colab.research.google.com/github/nareswaricarissaaviva/data_science_w1/blob/main/24216270_Nareswari_Carissa_A_(Tutor_3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

array_2x2 = np.array([[5, 2],
                      [7, 4]])
print(array_2x2)


[[5 2]
 [7 4]]


In [ ]:
random_array = np.random.rand(3,4)
print(random_array)


[[0.4682605  0.21628673 0.43038488 0.96429037]
 [0.19660736 0.46764801 0.74858123 0.16834086]
 [0.46536237 0.75407603 0.10557651 0.16149965]]


In [ ]:
ones_array = np.ones((3, 3))
zeros_array = np.zeros((3, 3))

print("Array of ones:\n", ones_array)
print("\nArray of zeroes:\n", zeros_array)


Array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array of zeroes:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
random_array2 = np.random.rand(6, 3)
print("Original array:\n", random_array2)

transposed = random_array2.T
print("\nTransposed array:\n", transposed)


In [ ]:
n, p, m = 2, 3, 4
A = np.random.rand(n, p)
B = np.random.rand(p, m)

dot_product = np.dot(A, B)

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nDot product:\n", dot_product)


Matrix A:
 [[0.51735085 0.27474352 0.99617974]
 [0.87497612 0.39385356 0.75566288]]

Matrix B:
 [[0.61592914 0.06631102 0.04781129 0.03733055]
 [0.11642984 0.80539601 0.17265093 0.41889297]
 [0.2311012  0.72808545 0.54676438 0.63060899]]

Dot product:
 [[0.58085814 0.98088738 0.61684554 0.76260103]
 [0.75941419 0.92541579 0.52300247 0.67417364]]
